### ISSUE TITLE
Output Format

### ISSUE THREAD

**Issue by msghera** [Misbah-Ahmad/money-in-words#1]
$test = new MoneyInWords();
echo $test->moneyToWords(11111111.6);

I tried a test with the upper code, now there is two 'and's which is not that shooting. Again instead of 'one hundred taka', 'One hundred Taka Only'' is more acceptable as the string format.

**Comment by Misbah-Ahmad** [comment]
I considered the 'only' word as the developers' responsibility.
'and' will be fixed.
